name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10 #このステップだけで起動するコンテナのイメージ
        with:
          entrypoint: '/bin/echo' #コンテナ起動時にechoコマンドを実行
          args: 'Hello World'
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10 
        with:
          entrypoint: '/usr/local/bin/node' #コンテナ起動時にnodeコマンドを実行
          args: -v
      - uses: actions/checkout@v2 #次ステップでファイル読み込むのでフォルダクローンが必要
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10 
        with:
          entrypoint: './script.sh' #作成したbashスクリプトを実行
          args: "Some string"
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} #WEBHOOK URL
          SLACK_MESSAGE: "Hello slack"

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api #講師が作ったDockerイメージからコンテナを実行
        ports:
          - 3001:3000
      mongo:
        image: mongo #mongoイメージからコンテナ実行
        ports:
          - "27017:27017"
    steps:
      - name: Post a user #Post
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get Users #Get
        run: curl http://localhost:3001/api/users