name: Shell Commands #ワークフローの名前

on: [pull_request] #ワークフロー実行のトリガーとなるイベント

jobs: #ワークフローで実行するジョブ(複数記述可能)
  run-shell-command: #ジョブの名前
    runs-on: ubuntu-latest #ジョブを実行するVMのOSをlinuxに指定
    steps: #ジョブの実行内容
      - name: echo a string
        run: echo "Hello World"
        # continue-on-error: true
        # timeout-minutes: 0
      - name: multiline script 
        run: |
          node -v 
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest #ジョブを実行するVMのOSをwindowsに指定
    needs: ["run-shell-command"] #run-shell-commandのジョブが成功したときだけ実行
    steps:
      - name: Directory PowerShell
        run: Get-Location #winOSなのでPowerShellを実行
      - name: Directory Bash
        run: pwd #bashのpwdコマンドを実行
        shell: bash #shellをbashに指定
